### ISSUE TITLE
转换错误

### ISSUE THREAD

**Issue by EaglePPP** [EXKulo/xmind_markdown_converter#2]
(base) PS C:\Users\1> python xmind2md.py -source E:\OneDrive\Xmind\M1.xmind
sys.argv:  ['xmind2md.py', '-source', 'E:\\OneDrive\\Xmind\\M1.xmind']

Traceback (most recent call last):
  File "xmind2md.py", line 76, in <module>
    main()
  File "xmind2md.py", line 66, in main
    strResult = Print2MDList(dictResult)
  File "xmind2md.py", line 40, in Print2MDList
    return ''.join(listStr)
TypeError: sequence item 154: expected str instance, NoneType found

**Comment by EaglePPP** [comment]
不晓得是太长了还是有图，别的文件没有问题
